In [33]:
import pandas as pd

In [34]:
data = pd.read_csv('one stack_data.csv')
old = pd.read_csv('previous_data.csv')
old

,Y_vals,mask_id,Stain,X_vals,file_name,DJID,Eye,eGFP_Value,eGFP_Raw_Intensity,in_rip
0,"91001, 94476, 97702, 99241, 106455, 108952, 11...",0,DAPI,"0.0, 0.15, 0.3, 0.44999999999999996, 0.6, 0.75...",2006L_GLUT1_647_WGA_594_0001,2006,L,True,60.608448,False
1,"25935, 27691, 32102, 33195, 41392, 45646, 5084...",0,eGFP,"0.0, 0.15, 0.3, 0.44999999999999996, 0.6, 0.75...",2006L_GLUT1_647_WGA_594_0001,2006,L,True,60.608448,False
2,"164618, 200794, 266470, 281358, 314684, 302362...",0,WGA,"0.0, 0.15, 0.3, 0.44999999999999996, 0.6, 0.75...",2006L_GLUT1_647_WGA_594_0001,2006,L,True,60.608448,False
3,"9783, 11396, 14458, 15066, 18389, 19341, 19969...",0,GluT1,"0.0, 0.15, 0.3, 0.44999999999999996, 0.6, 0.75...",2006L_GLUT1_647_WGA_594_0001,2006,L,True,60.608448,False
4,"46406, 47492, 49547, 50177, 53376, 55141, 5664...",1,DAPI,"0.0, 0.15, 0.3, 0.44999999999999996, 0.6, 0.75...",2006L_GLUT1_647_WGA_594_0001,2006,L,False,6.785691,False
...,...,...,...,...,...,...,...,...,...,...
7291,"2077, 2423, 3057, 3600, 4853, 5987, 9231, 1536...",68,GluT1,"0.0, 0.15, 0.3, 0.44999999999999996, 0.6, 0.75...",3318R_GLUT1_647_WGA_594_0001,3318,R,False,4.000467,False
7292,"26872, 27196, 27099, 27953, 28309, 29354, 3048...",69,DAPI,"0.0, 0.15, 0.3, 0.44999999999999996, 0.6, 0.75...",3318R_GLUT1_647_WGA_594_0001,3318,R,True,18.464860,False
7293,"4474, 4442, 4517, 4525, 4724, 4783, 5122, 5858...",69,eGFP,"0.0, 0.15, 0.3, 0.44999999999999996, 0.6, 0.75...",3318R_GLUT1_647_WGA_594_0001,3318,R,True,18.464860,False
7294,"11673, 12574, 14052, 16082, 20863, 26054, 4104...",69,WGA,"0.0, 0.15, 0.3, 0.44999999999999996, 0.6, 0.75...",3318R_GLUT1_647_WGA_594_0001,3318,R,True,18.464860,False
7295,"2218, 2575, 3126, 3744, 5119, 6362, 10181, 171...",69,GluT1,"0.0, 0.15, 0.3, 0.44999999999999996, 0.6, 0.75...",3318R_GLUT1_647_WGA_594_0001,3318,R,True,18.464860,False

In [41]:
data

,mask_id,Y_vals,X_vals,file_name,DJID,Eye,Time_Min,eGFP_Value,eGFP_Raw_Intensity,in_rip,Y_vals_DAPI,Y_vals_eGFP,Y_vals_WGA,Y_vals_GLUT1
0,0,NaN,"0.0,0.15,0.3,0.44999999999999996,0.6,0.75,0.89...",2007R_GLUT1_647_WGA_594_0002.nd2,2007,R,5,False,3.063058,False,[12.70017847 12.66745985 12.70999405 12.855145...,[1.82004759 1.85663296 1.88548483 1.90392623 1...,[ 5.62581797 5.49702558 5.88072576 6.428316...,[0.57049375 0.57198096 0.6154075 0.70523498 0...
1,1,NaN,"0.0,0.15,0.3,0.44999999999999996,0.6,0.75,0.89...",2007R_GLUT1_647_WGA_594_0002.nd2,2007,R,5,False,3.536082,False,[13.10790378 13.20389462 13.38258877 13.540893...,[1.82542955 1.84444444 1.86620848 1.84742268 1...,[ 5.26071019 5.19747995 5.49415808 5.958533...,[0.52119129 0.51592211 0.54776632 0.65681558 0...
2,2,NaN,"0.0,0.15,0.3,0.44999999999999996,0.6,0.75,0.89...",2007R_GLUT1_647_WGA_594_0002.nd2,2007,R,5,False,12.084552,False,[13.24528051 13.36134007 13.48869981 13.736639...,[ 2.02087211 2.04187716 2.08867323 2.093725...,[ 5.04573252 5.00505185 5.3126828 5.755650...,[0.66192502 0.65128955 0.73384738 0.8546929 1...
3,4,NaN,"0.0,0.15,0.3,0.44999999999999996,0.6,0.75,0.89...",2007R_GLUT1_647_WGA_594_0002.nd2,2007,R,5,False,3.425488,False,[12.78108941 12.91264132 12.82733813 13.180883...,[ 1.96608428 2.04110997 2.04727646 1.957862...,[ 5.12230216 5.0668037 5.2672148 5.795477...,[0.49537513 0.52312436 0.55498458 0.66495375 0...
4,6,NaN,"0.0,0.15,0.3,0.44999999999999996,0.6,0.75,0.89...",2007R_GLUT1_647_WGA_594_0002.nd2,2007,R,5,False,3.427007,False,[13.11678832 13.26277372 13.19708029 13.540145...,[1.86131387 1.88321168 1.95985401 1.95255474 2...,[ 5.60583942 5.36131387 5.60948905 6.047445...,[0.62773723 0.51459854 0.54014599 0.7080292 0...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122,127,NaN,"0.0,0.15,0.3,0.44999999999999996,0.6,0.75,0.89...",2007R_GLUT1_647_WGA_594_0002.nd2,2007,R,5,False,4.997976,False,[13.51272412 13.88548294 14.16252169 14.574609...,[1.97252747 1.9832273 2.0242915 2.0373048 2...,[ 4.77096588 5.09774436 5.40746096 5.741179...,[0.46790052 0.56072874 0.61336032 0.70387507 0...
123,128,NaN,"0.0,0.15,0.3,0.44999999999999996,0.6,0.75,0.89...",2007R_GLUT1_647_WGA_594_0002.nd2,2007,R,5,True,53.319268,False,[12.59540702 12.89413742 12.8707991 13.055638...,[ 2.0688947 2.08252427 2.1435773 2.153099...,[ 5.02931292 5.47927558 5.83084391 6.201456...,[0.50317401 0.58999253 0.67326363 0.77912621 0...
124,129,NaN,"0.0,0.15,0.3,0.44999999999999996,0.6,0.75,0.89...",2007R_GLUT1_647_WGA_594_0002.nd2,2007,R,5,False,3.017331,False,[14.35112652 14.95771231 15.91681109 16.420797...,[ 1.92443674 1.93414211 1.96533795 1.949393...,[ 4.6135182 4.96291161 5.19237435 5.521663...,[0.44367418 0.54280763 0.64714038 0.705026 0...
125,130,NaN,"0.0,0.15,0.3,0.44999999999999996,0.6,0.75,0.89...",2007R_GLUT1_647_WGA_594_0002.nd2,2007,R,5,False,14.762393,False,[12.5620133 12.8311491 12.91016144 13.080721...,[ 1.99088319 2.05735992 2.0991453 2.105413...,[ 4.71832858 5.11927825 5.42165242 5.789743...,[0.48091168 0.5711301 0.64539411 0.73504274 0...
126,133,NaN,"0.0,0.15,0.3,0.44999999999999996,0.6,0.75,0.89...",2007R_GLUT1_647_WGA_594_0002.nd2,2007,R,5,False,2.881172,False,[13.67447699 13.94644351 14.56736402 14.574895...,[1.83012552 1.86861925 1.90292887 1.86443515 1...,[ 4.77154812 5.21924686 5.43933054 5.860251...,[0.49790795 0.55481172 0.66276151 0.75732218 0...